apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0ZGxjVJwaXU1ouRdeS9jAGr6OOmwqX3Ns39UK+OixiCHEQH8,iv:6tlyPk3nHBZZYeHcO4uNkrDXTGisQb97vVOKup6BX0Q=,tag:ePeVzid4VZBpw9bg0gnFdg==,type:str]
    credentials.json: ENC[AES256_GCM,data:Cd3nBKT6jnjHs7XR/4W55BchRfw6G+4mOMM6tOttkk2NL6f9YzvePfBacVvccemMpi66wby/KZ7A5AwAVMruZ12iZwrAGQCoSDeybKPuX+kIzm7Vwtp1oFqJBlAQ5GVcosyZlYiHt8B5cAdma7nhUYntoNfOLnMk2e6B5f2hDDI/eO6LE1BIGbP5p7oY8y7p8LSGXFNKjxu858UBUUySvBYs7Z5gejFlFFCEZrHXnQ==,iv:gTwLHeM49usggmRrVwxGCxWR2Khc/tflTHMbtUuUTb0=,tag:lOpYCZjDUOOsD9emZqW7+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l93jk4frued70h4v64any2aew9c7d2v8hwr0d7p3pj86fvktrcvs7tu2nq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTnhUME90MWMvVEs5TFI3
            SUlJYnNHbmZYRjdHYkdsWU1LYmgwcUpkYTB3CnUyTmRIek42NFBuZTdjNGg2NDU0
            R2VOWEJOR2VNZjh0NzduajBtUndQaVkKLS0tIFZEUXdmSndZeGlpMXJOWGlmOEZH
            RTl4R1VRREhQSjRtZXA4cnpaK0w4UzAKfP/patNprEZqyW/tJ9Erd6/U3A2Z1TRB
            OUhbqBjmj9syzCMSgvXASd3c00YHOoMJqdo5xbT3m9/XI1Vq4rNSzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T07:18:13Z"
    mac: ENC[AES256_GCM,data:3tts6l7eOkyrXYlDX/f0HV8nr6+iTc3r2WOIua2yJ6fa1PcGkwrIzTrMz2eyXzGVm5dp5sOdcJXdeTwlVxoAEoBEMnDOO0FiLKFUFeViAXb+qsnFZ9+H36kcHKWawmgtVLykk62vN19bAk81YTDK0TIOfZA33iXB3YwfpCqHqD8=,iv:yQw9SwxZ7dpJPeppD/e+aP1Kz2SXHZ/R9cbImmXXjCw=,tag:o6Dhdt21804XMERItJHlRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
