apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1wtsE035P2wx1cTsBl5NBptPI8bEbkOSuqW/LtqFNBQJHccI,iv:koc1EqJaBe/C0kfBvnZoPNDjlZZfEas5dvW7AV170H0=,tag:tOKmeGNhcq8zCgN309NW6Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:keu/k/rscUeQ0be2tGB90ypdIJilYXjp7hWDr3EisTEyWOKZCNzRYbX7/gPD1pCgIZ9lNE8uUZoWOnms2b+8U5pHGiROGyfmWDUm3fN2PP/CmiWhP+kBGq7GdRslHFVi3FyYeRK5kCCpcgkirE0EeXztlFDqwkzF91zICqvu2SUp/bHXHR0bXGb7d/Ig0L7YQ+6HYJYvGyaGuO+uJwOJR9FjSfD6UK2a9Df+Y+KR4g==,iv:zEh0Ut1pWJItoCgnqzQjGPWHoaahGlC0iejnsH4nlOU=,tag:RUfJu3HDkO2pquBHds4rHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l93jk4frued70h4v64any2aew9c7d2v8hwr0d7p3pj86fvktrcvs7tu2nq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRi9KcVQyNVJscVhNbDQy
            TzlsMkNhdE10ZGhwSTlySmlMT01JaUhoUVJBClkzTlY4NmFYOEowem84ZWh5MVJU
            cHlKTXVzTk1qRTJrbk0zWGx0OVc5WG8KLS0tIFE2d0duL3NNRk1qdDFRS09aNDg5
            VGFSUnlkc0g1ME1nYTU0aVoxVGxKOWcK2EKuLAM3E0psicMyhSCcF5PvLKULfsHT
            YlO5c096mEqrCV59yjkl6cuhOHihqInE2GviNSlMKrrlTG0/irQ9/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T16:22:09Z"
    mac: ENC[AES256_GCM,data:KESs/Tj9FSPlttvvvY2DxhzlMisw9SD2b+8JgA/vhbFBgo+5+XSvpwn3WXvlqvkJd32mec7gFGfoEMtfj9L9iW1K0m2EmdO5HoJhkp0vYx3+tH3wjleOYKtSoiOoovv4ONUOIARTBSEJGyX9OytZXuzCMQjl/5IbmbuhhUZ+Dh4=,iv:owaIjNOGjr0WFtaD6M2wbW9iTzUfEMrEvYFJ2bD3/R8=,tag:lASC99C9iaPsDxOGKwjZPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
