apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Dsb8yyTTEm67b5vY,iv:ENyO0VW3UmaXA7Av2SMAldugQSrvef/sI1eMn1V42Ak=,tag:VlDT9H7WrX8SIPEU1Hn9cA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:xkqpLgKGFZsJIJgHUVNe1EieaooD8jMXZA==,iv:SUAKBKnq5yCtYxu4dDMK/Iz47o/p/VAslT+o+kDyGBY=,tag:7mihfkFjhj1GuH+Pfv2eMg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:1ov1Z9qaZV7A/oETlyOTf5GqYGvzC0P/uRJWkQg4SdAktSq4,iv:ujUvsGVGmuR2oOHW+UCj1ASNzjluQBQWuOuy34g2j6k=,tag:gBwwHIqPIj/JCquEQLHNJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l93jk4frued70h4v64any2aew9c7d2v8hwr0d7p3pj86fvktrcvs7tu2nq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUlFvYzB2OW1BMTdRQ1hO
            MC8wMUl2anNIZUo2WVFvVVRwYWxkb3dXZkdVCnBTY0w3aUgxSG9xWnZHY2twUmJ0
            UWk4WHh2KzlSVFdDTVUwU2ZMdFRJUVEKLS0tIGxHc0pHQ0UxK3BZbGxoUnc1VEhJ
            c1ZaWldDdHNCeC9KOXlCT2FuSU1BZDgKUBZXXNAEv3imxTJILx5fixoJnC6lmjMI
            If5YGOyDHmfFfnzMajHqDI8XsLbLWMqM30LiOvk6thxCgF35Iet/oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T07:18:14Z"
    mac: ENC[AES256_GCM,data:jmB3DZxPZDmUlJDClIp8ZmlifUVS8cjajOinQwGBq1Mc4fftyfgrTzgjCMN2eoGXWiiDMnPHPIwSrKlFdwLhhRptoe8SaoMGxknR1PjthWhApXylfdTB7nxF4zkMb/GTHVH4KDA3D+188lYYxTP3YIAsRPEGbS13d/KSbJWIXMU=,iv:WuZMJMAX38w/L7lTrzx54XisjVHvjGofbjagrCvneRw=,tag:JJ4Nh4J+zJmMAR2GkkSRnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
