apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:khkBeJGln4D5iOk/QvOtXfkl7k8VyTDamodP2Y3Anog=,iv:HjpZ0rm4/U84EX/tJH9SsZBV+31EKYvUlPQvYFahqms=,tag:AfHhytxxq/DvlHFMvE0XiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15acja7dt204chuhfn0t8cljj737z3t4e7axtlw5pyhtrxg0s2yyqd9w9mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VVdraWdJQUREK0oycFFK
            QmZsajFGWGdWMzQvcVROSGVIQ3Jzcitjb2xFCmFxcDAxZytINGt6aUFtUnorVlFx
            QlVaTUt0WFU2MUtrdjIwK1JEUWthcW8KLS0tIDlVNlRodlRrQ1g1dkVsdWdRbFFF
            WGhVbUl2d1BXbXJWT1ZiRzAzUkdnbGMKAfiEq2JDOxs/QqXOEfBFi5z2OK8BBJAe
            YfBC8y1yJp4TNxYJHrud25LNQJxWhQY3OwAJ9/ewX3pOnLnlDLTkKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T05:24:11Z"
    mac: ENC[AES256_GCM,data:4GtcvyVU5XaQj4m+8Agn9I3CE1T8pjY1zWluHIOwKmVIhOy8cwqIELRkt928U5BYfdk6i+0mpQUGxflJ1c8bfeLvafJUY/oF1K1RqQEDsc8fIpw8YVEwaTLq7SnC/RyLO0zep+LDkEt7gS4ooW+aTlwjqZxzwRsjjUTCWpwH9eI=,iv:pp27ZZ4+K8UiVsAXSsmvl/6gvT+5oypf3XjNkxBqZ9Y=,tag:Dh8cJqmn8cB2iW5SWpdMsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
