apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:3URR51wXjeNItQd/Hyc8doT9PMR9oEosPZFZvAq65QsgFUUqEYdGug==,iv:4eBolFlGslMPcDj5by90Waxe2fRPomTzW9TYPgAK94Y=,tag:rQ3St3YJhiOMrCPAXtFT4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15acja7dt204chuhfn0t8cljj737z3t4e7axtlw5pyhtrxg0s2yyqd9w9mf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V1BtSzZJZWVsUEMxa0p6
            S1FLS0N6c3p0enN1ejVvNWFYOHJrNXNUVUdBCnlDUHFmRzhFZHJiQTF4cWlFZXNr
            NlV1YWZFWG9tMW5QaGdrQWZmLzVXWWsKLS0tIEYrY0ZQKzdxcmhtVWN6N2xBeGZa
            RjJDWEkwLzFubEt4TDN1VFdNd3pwSkEKucCPJ2dZDIvFOnerBrjKxoOX4qHSaj3F
            xtlhQbhhpi30Gs2/w3sIfFZ7OxhYjNS9RnqpRESC/A1uHId58YIRHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-13T05:24:11Z"
    mac: ENC[AES256_GCM,data:Ws/HsgzHCtbCy9HeZqj/k+QL90VUa+GYKh1G8d460iPOmP5vlzs6ALxKJi6kbFJod6Cq2vmhUYgUch8nXrtpkHokzRckcW2hzEY9f6qwhQaP9+CqJXfwUeA7NVl+W5DaCvYqus34JUtrYELmQjgt3zV91vPsLjijxFCv5lDP+o0=,iv:PNB5UfmCP7gI678lNylnk0H7/otPHPrmNAF0OSEhwfc=,tag:IOAxbZTHED8aIHbAYuNFVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
